name: 'Install'
description: 'Sets up Node.js and runs install with cache'

inputs:
    PACKAGE_TOKEN:
        description: 'GitHub Package Token'
        required: true

runs:
    using: composite
    steps:
        - name: Setup node
          uses: actions/setup-node@v4
          with:
              node-version: 18
              check-latest: true

        - name: Setup corepack
          shell: bash
          run: |
              npm i -g corepack@0.31
              corepack enable

        - id: get-store-path
          shell: bash
          run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_OUTPUT

        - uses: actions/cache@v4
          id: cache-pnpm-store
          with:
              path: ${{ steps.get-store-path.outputs.STORE_PATH }}
              key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
              restore-keys: |
                  pnpm-store-
                  pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

        - name: Set npm config
          shell: bash
          run: npm config set @goorm-dev:registry=https://npm.pkg.github.com/ && npm config set //npm.pkg.github.com/:_authToken ${{ inputs.PACKAGE_TOKEN }}

        - name: Install dependencies
          shell: bash
          run: pnpm install
